# config/constants.py

import pandas as pd
from config.settings import BASE_DIR

def load_list(filename, column):
    path = BASE_DIR / filename
    if not path.exists():
        print(f"File not found: {path}")
        return []
    return pd.read_csv(path)[column].tolist()

# List of OEMs to look for in text
oem_list = ['Volvo', 'Mack', 'Volvo-Mack', 'Hino', 'Isuzu', 'Cummins', 'Road Choice', 'Rig Force',
            'Dorman', 'Autocar', 'Horton', 'Pai-Industries', 'Pai Industries','Fleetguard','Automann', 'Donaldson', 'Caterpillar',
            'Detroit-Diesel', 'International', 'Paccar', 'Dodge', 'Chevrolet','GMC','Chevrolet-GMC', 'Ford', 'Acura', 'Audi', 'BMW','BMW-Mini',
            'Buick', 'Chrysler', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Kia', 'Land Rover', 'Lincoln', 'Mazda',
            'Mercedes', 'Mitsubishi','Nissan','Nissan-Infiniti', 'Pontiac', 'Porsche', 'Toyota-Lexus','Lexus','Seiki',
            'Volkswagen', 'Duramax', 'Allison', 'Mahindra', 'Sprinter', 'Freedom', 'GMC', 'Toyota', 'Powerstroke', 'Navistar',
            'Aisin-Seiki', 'Aisin','All-Other', 'Alliance','Alliance-Axle', 'Allis-Chalmers', 'Allison', 'ASV', 'Autocar', 'Bedrock-Truck-Beds',
            'Bendix', 'Blue Bird', 'Bobcat', 'Bosch', 'Bradford-Built', 'Buyers', 'Cadillac', 'Capacity', 'Case', 'CAT',
            'Chevrolet', 'Clark', 'Continental Engines', 'Crane Carrier', 'DAF', 'Demco', 'Detroit', 'Deutz', 'Doosan',
            'Dorsey', 'Dresser', 'Duplex', 'Eaton', 'Eaton-Mid-Range', 'Fiat-Allis', 'Fiat-Iveco', 'Freightliner',
            'John Deere','Kenworth','Peterbilt',"Caterpillar", "Cummins", "Detroit Diesel", "Deutz", "Isuzu", "John Deere", "Kubota","Northern-Lights","Perkins",
            "Westerbeke","Yanmar", "Murphy-Controls", "Twin-Disc", "Starters-and-Alternators", 'Fiat','Volvo/Mack''Chevrolet/GMC',
            'BMW/Mini','Nissan/Infiniti','Toyota/Lexus','Bradford Built','Fiat/Iveco', 'Match Made', 'Match-Made', 'Match',
            'Ottawa', 'A&E', 'Sew-Eurodrive', 'Garmin', 'BORG WARNER', 'whelen engineering', 'Rite Hite','Donaldson', 'Davco', 'CAT', 'CUMMINS', 'Paccar Engine',
            'DETROIT DIESEL', 'PACCAR', 'Prestolite / Leece-Neville','Grand Rock', 'American Cooling Systems', 'Delco Remy',
            "DETROIT DIESEL", 'EATON', 'TRP', 'Stemco','Dana Spicer', 'Trux Accessories', 'Norma', 'SPICER',
            'United Pacific', 'Pillips & Temro',"Paccar Engine' 'Paccar Engine", 'Arens Controls', 'Dynacraft',
            'Artic Fox', 'FREIGHTLINER', 'Meritor', 'PETERBILT', 'Kenworth','HALDEX', 'Fleetguard', 'Atro', 'Baldwin Filters', 'Bergstrom',
            'Fuller', 'Denso', 'TIMKEN', 'Bosch', 'TCCI','Mitsubishi Electric', 'Index Sensors & Controls',
            'WILLIAMS CONTROLS', 'Dayco', 'Watson Chalin', 'HORTON', 'SKF','Conmet', "PACCAR' 'PACCAR", 'BORG WARNER', 'Phillips Industries',
            'Jacobs', 'CDTi', 'FlexFab', 'BENDIX', 'Spectra Premium','Mahle Behr', 'M&M Fastener', 'Tectran', 'Kongsberg Automotive',
            'Star Coolant Tubes', 'Atco', 'HotStart', "CUMMINS' 'CUMMINS",'Fumoto', 'WABCO', 'HINO', 'Kitmasters', 'Parker Hannifin',
            "Meritor' 'Meritor", 'Interstate Mcbee', 'Racor', 'Webasto',"DETROIT DIESEL' 'FREIGHTLINER", 'VOLVO', 'TRW', 'Trelleborg',
            'First Motion Products', 'Eberspächer', "Dynacraft' 'Dynacraft",'ALLIANCE', 'Weller', "Kenworth' 'Link Manufacturing", 'Grote',
            'Cole Hersee', 'Velvac', 'GT Development', 'Federal Hose','R.G. Ray', 'Fasco Industries', 'NTN', 'ISSPRO',
            'Pacific Diesel Brake', 'Isuzu', 'Sew-Eurodrive','whelen engineering', 'Garmin', 'Rite Hite', 'Eaton Vickers',
            'Hydro-Max', 'Truck To Trailer', 'MEI Truck Air', 'MEI', 'SANDEN','Parker', 'Kunkle', 'HOBART', 'AFTERMARKET', 'FRIGHTLINER',
            'Deutz', 'Ams Rhinopac', 'Mopar', 'Muncie Pto Power Take', 'DANA','International', 'Navitas', "FREIGHTLINER",
            'Daikin', 'JLG', 'VALEO', 'Webb Wheelinboard', "SPICER' 'SPICER",'Pai-', 'Pai_','Raymond', 'Club Car', 'Mei Airsource', 'FLUIDYNE',
            'Bd Diesel', 'Kubota', 'DAYTON', 'Zexel', 'Kit Masters','BORGWARNER', 'Caterpillar', 'CTP', 'Tesla', 'Carrier',
            'Honeywell', 'D&W', 'Ridgid', 'Yanmar', 'Rexroth Bosch',"Motor Coach Industries' 'Motor Coach Industries", "Bosch' 'Bosch",
            'ACDELCO', 'B&W', 'Sheppard', 'Danfoss', 'DAF', "TRW' 'TRW",'Nidec', 'KYSOR', 'UNBRANDED', 'Mercruiser',
            'ALLISON', 'Ventech', 'airend', 'Kawasaki','Inrernational', 'Curt', 'NISSAN', 'MERCEDES BENZ',
            'Bosch Rexroth', 'Davico', 'Garrett',"International",
            'Genuine International', 'Magnaflow', 'PARKER CHELSEA', 'JCB','WEASLER', "Sonny's", 'ATP', 'Polaris', 'Volvo Mack', 'RETRAC',
            'MACK', 'GENUINE CAT',"PACCAR", 'TRANSTECK', 'Bilstein', 'GM', 'Espar',
            'Custom Control Concepts', 'Fmf', 'INTER LINK', 'Gasi','FIRESTONE', "International",
            'Workhorse', 'Maxon', 'Hendrickson', 'Mitsubishi', 'CHELSEA',
            'CNH', 'Truck Lite', 'HD PLUS', 'Mahle', 'Indian','MTU',
            "CUMMINS' 'CUMMINS' 'CUMMINS", 'Yamaha', 'Atlas Copco',
            'Allison Transmission', 'Stemco Kaiser', 'DELETE', 'Buyers',
            'Bondioli & Pavesi', 'Edge', 'Pacific Projection', 'APX', 'O.E.M.',
            'Vdo', 'Transtar', 'Honda', 'MAGNUM', 'Dinex',
            'Greenfield Threading', 'Roper', 'Muncie', 'Navistar', 'Holset',
            "DETROIT DIESEL' 'CUMMINS", 'ROCKWELL WABCO', 'Freight Defense',
            'Bab Steering', 'Thermo King', 'Wabco Meritor', 'Meritor Wabco',
            'Aam American Axle', 'BULLY DOG BIG', 'Genie',
            'Area Diesel', 'Ud Trucks', 'LUVERNE', 'Sealco', 'Nive',
            'TYCO FIRE', 'Zumbrota Gear Zbag', 'AUTOMANN', 'Toyota',
            'Thoroughbred Diesel', 'NEW HOLLAND', 'SAF HOLLAND', 'Neville',
            'Turbopark', 'MUNCIE POWER', 'Scott DC', 'Bose',
            'Bitzer', 'INTERLIFT PALFINGER', 'hiab',
            "Genuine International' 'Genuine International", 'Tamerx',
            'DORMAN', 'RIDEWELL', 'White', 'TSI Products', 'Tru-Fit',
            'GENUINE BORG WARNER', 'Newborn', 'MACK | HOLSET', 'Robinair',
            'Auburn Gear', 'Dynamatic', 'Nilfisk',
            'Lewmar', 'Husqvarna', 'reese', 'MOTORCRAFT', 'PHILLIPS',
            'Lincoln', 'Gillig', 'Global Parts', 'Bobcat', 'BWD AUTOMOTIVE',
            'Bullet Proof Diesel', 'MOPAR | CHRYSLER GROUP', 'Amer',
            'Totaline', 'Can Am', "Inrernational' 'Inrernational", 'Doosan',
            'CARLISLE', 'AAM', 'CAT GARRETT', 'ROSTRA', 'Radiator Pros',
            'Tuff Torq', 'Injection Pump', 'Borgeson Universal', 'Stucchi',
            'Clark', 'Woodward', 'NSS', 'CASE', 'Mercury',
            'Full Tilt Performance', 'RAM', 'BUYERS PRODUCTS', 'Ford',
            'BEHR HELLA', 'Cloyes', 'OTTAWA KALMAR', 'STAR WARNING',
            'Mercedes-Benz', 'Warn', 'SMARTTANK', "PACCAR' 'WABCO", 'Neway',
            'Ati Performance Products', 'ATI', 'trucklite', 'Delphi', 'Krone',
            'Porsche', 'Maval', 'Fox', 'Fox Racing', 'Eaton Fuller',
            'Walterscheid', 'Kayotawa',
            'WESTERN START', 'Meritor | Rockwell', 'AutoCar', 'Daimler Truck',
            'AIRDOG', 'Groeneveld', 'JOHN DEERE', 'MEI TRUCK',
            'Comer Industries', 'Arnott', 'Redneck Trailer', 'AKG', 'BURLY',
            'Dacco', 'TansAxle', 'Baldwin', 'Leece Neville-Prestolite',
            'Tuffline', 'C.E Niehoff & Co.', 'KeTop', 'Flagg Triangle',
            'AIRTEC', 'Apr', 'Hitachi', 'Mazda', 'VINJET', 'Torklift',
            'Permco', 'Diamond', 'Diamond Advantage', 'Shaw', 'SACHS',
            'TIMBREN', 'DT COMPONENTS', 'Deep Sea', 'DTI', 'EUCLID',
            'E-Controls', 'Bostech', 'Baldor', 'Emco Wheaton', 'Roadworks',
            'Flagg Suspension', 'FLEETRITE', 'Spectra', 'Mach', 'Galbreath',
            'Noco', 'Usa Standard Gear', 'GPS', 'Gates',
            'Marathon Globetrotter', 'Rbc Bearings', 'PARAGON',
            "Bab Steering' 'Bab Steering' 'Bab Steering", 'Hydro-Gear',
            'PROCESS SOLUTIONS', 'Heavy Motions', 'Century', 'South Bend',
            'IMMI', 'Standard', 'Link-Belt Crane',
            "Eaton Fuller' 'Eaton Fuller", 'GENUINE BENDIX', "BENDIX' 'BENDIX",
            'REI', 'Knorr-Bremse', 'Takeuchi', "EATON' 'EATON", 'Diamond Eye',
            'KFI', 'Fontaine', "Meritor Wabco' 'Meritor Wabco", 'Copeland',
            'Mirimoto', 'Morimoto', 'Power Train', 'Land Rover', 'Lostar',
            'Cleco', "Interstate Mcbee' 'Interstate Mcbee", 'Conlux',
            'Shepard', "SANDEN' 'SANDEN", 'Service First', 'PolyScience',
            'Midwest Truck', 'OPW', 'OTR', 'Roush', 'PowerBond',
            'SILENT DRIVE', 'Pedal Commander', 'Super Atv', 'Trico',
            'PENA PACIFIC', 'Wabash', 'Bezares', 'PRIMATECH',
            'Interstate-McBee', 'Motive Gear', 'Rotomaster', 'Ram Mount',
            'Rancho', 'Hema', 'Stanadyne', 'Readylift', 'REKLUSE',
            "HALDEX' 'HALDEX", 'Newstar', "HINO' 'HINO",
            "BORGWARNER' 'BORGWARNER", 'Spod', 'Enerpac', 'Luxerad', 'Hytorc',
            'STAR', 'STIGAN', 'Fomoco', "BEHR' 'BEHR", 'BEHR', 'Ete', 'Apsco',
            'L’Orange', "Hendrickson' 'Hendrickson", 'National Drivetrain',
            'WESTERN FLUIDYNE', 'TECTRAN WILLIAMS', 'Ex-Guard', 'Blackmer',
            'Skyline', 'YUKON GEAR', 'YUKON', 'Crown', 'Spartan', 'Skully',
            'A.O. Smith', 'Liebherr', 'Char-Lynn', 'ClassParts',
            'Bright Lights', 'AME International', 'Novo', 'SunSource',
            'Balcrank', 'Roadforce', 'GARRET, MACK', 'Edge Products', 'Alfdex',
            'Otc Spx', 'Junyan', 'RANGER', 'Maytag', 'Ingersoll Rand',
            'Force America', 'Headlight Depot', 'Fuel Manager', 'PullRite',
            'Tramec Sloan', 'Nokia', 'ACTIA', 'DCEC Cummins', "Raney's",
            'Case IH', 'DRS', 'Trax', 'SELTEC', 'PAI INDUSTRIES',
            "Mei Airsource' 'Mei Airsource", "Bd Diesel' 'Bd Diesel", 'DODGE',
            'Motor Coach Industries', 'BIMBA', "BORG WARNER' 'BORG WARNER",
            "International' 'Pai' 'Pai", "POLLAK' 'POLLAK",
            "Garrett' 'Garrett", "DAF' 'DAF", 'RANDOM', 'BRP',
            'PARKER CHELSA', "Maxon' 'Maxon", 'Ecu Max', "ALLISON' 'ALLISON",
            'ROCKWELL', 'MODINE', "WABCO' 'WABCO", 'NORDICTRACK PROFORM',
            "Thermo King' 'Thermo King", 'HARLEY DAVIDSON', 'HOT RODS',
            'Dayton Parts', 'ARLEN NESS', 'RIGID INDUSTRIES', 'K&N', 'GARRET',
            'RADIATOR PROC', 'Agility', 'FRIEDRICH',
            'AGVANTAGE', 'RELIANCE', 'AKMI', 'ALLIANT POWER', 'LEECE NEVILLE',
            'GOODMAN', 'BC RACING', 'HOOVER COMMERCIAL', 'DEXTER AXLE',
            'EATON DANA', 'RED DOT', 'GAST', 'GB', 'GENUINE AAM', 'CARTER',
            "ATP' 'DCL", "Meritor Wabco' 'Meritor Wabco' 'Meritor Wabco",
            "ATP' 'ATP' 'ATP", 'GRACO', 'EXEDY', 'PLATINUM HD', 'Besco', 'IAG',
            'NAPA', 'Kent-Moore', 'KALMAR', "KYSOR' 'KYSOR", "Ford' 'Ford",
            'LO-STAR', 'Metaris', 'Trane', 'MONROE', 'PROTORQUE', 'ZF',
            "PETERBILT' 'PETERBILT", 'RGBLINK', 'ROAD-FORCE', 'Oregon', 'S&S',
            'Coxreels', 'TORQUE', 'TL-27601CB', 'TREMEX', 'H&S AUTOSHOT',
            'USA', 'USA STANDARD', 'JOHNSON CONTROLS', 'SMC', 'WORLD AMERICAN',
            'WILLIAMS TECTRAN', 'Hydreco', 'BendPak']

oem_list = [i.title() for i in oem_list]

# Engine Models (c_c_p_all stands for common engine models)
c_c_p_all = load_list('Engine Model All.csv', 'Engine Model')

c_c_p_all = [str(i) for i in c_c_p_all]
# Displacements
dis_all = load_list('Engine Displacement All.csv','Eng Displacement')
dis_all = [str(i) for i in dis_all]

ext_cols = ['Clean Part Number','Clean OEM', 'Clean Part Description', 'Source Name']